//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNVTH.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TNVTHEntities : DbContext
    {
        public TNVTHEntities()
            : base("name=TNVTHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Adver> T_Adver { get; set; }
        public virtual DbSet<T_Album> T_Album { get; set; }
        public virtual DbSet<T_Config> T_Config { get; set; }
        public virtual DbSet<T_HotLink> T_HotLink { get; set; }
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<T_News> T_News { get; set; }
        public virtual DbSet<T_News_Tag> T_News_Tag { get; set; }
        public virtual DbSet<T_Slide> T_Slide { get; set; }
        public virtual DbSet<T_SlideGroup> T_SlideGroup { get; set; }
        public virtual DbSet<T_Tag> T_Tag { get; set; }
        public virtual DbSet<T_UserProfile> T_UserProfile { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}
