//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNVTH.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_News
    {
        public T_News()
        {
            this.T_News_Tag = new HashSet<T_News_Tag>();
        }
    
        public int ID { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public string AvataImageUrl { get; set; }
        public Nullable<bool> IsHotNews { get; set; }
        public string ContentNews { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<T_News_Tag> T_News_Tag { get; set; }
    }
}
