//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNVTH.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_News_Tag
    {
        public int ID { get; set; }
        public int TagID { get; set; }
        public int NewsID { get; set; }
    
        public virtual T_News T_News { get; set; }
        public virtual T_Tag T_Tag { get; set; }
    }
}
